server:
  port: 6789

spring:
  application:
    name: mirai-omnitrix
  profiles:
    active: local
  datasource:
    url: jdbc:sqlite:omnitrix.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      schema-locations:
        - classpath:sql/init.sql
      mode: always
      platform: sqlite
      encoding: UTF-8

bot:
  qq:
  password:
  hello:

http:
  proxy:
    host: localhost
    port: 7890

permission:
  admin:
  repeatExcludeGroup:
  chatExcludeGroup:
  bvExcludeGroup:
  emojiMixExcludeGroup:
  chatPlusNotNeedCommandGroup:
  replyExcludeGroup:

account:
  characterAiToken:
  saucenaoKey:
  bgmAccessToken:
  openaiApiKey:
  azureSpeechKey:
  azureSpeechRegion:
  bingSearchKey:
  googleSearchKey:
  githubToken:
  v2exToken:
