server:
  port: 6789

spring:
  application:
    name: mirai-omnitrix
  profiles:
    active: local

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

bot:
  qq:
  password:

permission:
  admin:

http:
  proxy:
    host: localhost
    port: 7890