server:
  port: 6789

spring:
  application:
    name: mirai-omnitrix
  profiles:
    active: local
  datasource:
    url:
    username:
    password:

bot:
  qq:
  password:

permission:
  admin:
  repeatExcludeGroup:

http:
  proxy:
    host: localhost
    port: 7890

account:
  characterAiToken:
  saucenaoKey:
  bgmCookie: