server:
  port: 6789

spring:
  application:
    name: mirai-omnitrix
  profiles:
    active: local
  datasource:
    url: jdbc:sqlite:omnitrix.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      schema-locations:
        - classpath:sql/init.sql
      mode: always
      platform: sqlite
      encoding: UTF-8

bot:
  qq:
  password:

permission:
  admin:
  repeatExcludeGroup:
  chatIncludeGroup:
  bvIncludeGroup:

http:
  proxy:
    host: localhost
    port: 7890

account:
  characterAiToken:
  saucenaoKey:
  bgmCookie:
  openaiApiKey: